#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kkgamesProj
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="kkgamesforais")]
	public partial class gamesdbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void Insertauthkeydb(authkeydb instance);
    partial void Updateauthkeydb(authkeydb instance);
    partial void Deleteauthkeydb(authkeydb instance);
    partial void Insertyacheykadb(yacheykadb instance);
    partial void Updateyacheykadb(yacheykadb instance);
    partial void Deleteyacheykadb(yacheykadb instance);
    partial void Insertenergydb(energydb instance);
    partial void Updateenergydb(energydb instance);
    partial void Deleteenergydb(energydb instance);
    partial void Insertexpdb(expdb instance);
    partial void Updateexpdb(expdb instance);
    partial void Deleteexpdb(expdb instance);
    partial void Insertglobalitemdb(globalitemdb instance);
    partial void Updateglobalitemdb(globalitemdb instance);
    partial void Deleteglobalitemdb(globalitemdb instance);
    partial void Insertinventorydb(inventorydb instance);
    partial void Updateinventorydb(inventorydb instance);
    partial void Deleteinventorydb(inventorydb instance);
    partial void Insertmoneydb(moneydb instance);
    partial void Updatemoneydb(moneydb instance);
    partial void Deletemoneydb(moneydb instance);
    partial void Insertracedb(racedb instance);
    partial void Updateracedb(racedb instance);
    partial void Deleteracedb(racedb instance);
    partial void Insertracetypedb(racetypedb instance);
    partial void Updateracetypedb(racetypedb instance);
    partial void Deleteracetypedb(racetypedb instance);
    partial void Insertsettingsdb(settingsdb instance);
    partial void Updatesettingsdb(settingsdb instance);
    partial void Deletesettingsdb(settingsdb instance);
    partial void Insertshipdb(shipdb instance);
    partial void Updateshipdb(shipdb instance);
    partial void Deleteshipdb(shipdb instance);
    partial void Insertstagedb(stagedb instance);
    partial void Updatestagedb(stagedb instance);
    partial void Deletestagedb(stagedb instance);
    partial void Insertuserdb(userdb instance);
    partial void Updateuserdb(userdb instance);
    partial void Deleteuserdb(userdb instance);
    #endregion
		
		public gamesdbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["kkgamesforaisConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public gamesdbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public gamesdbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public gamesdbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public gamesdbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<authkeydb> authkeydb
		{
			get
			{
				return this.GetTable<authkeydb>();
			}
		}
		
		public System.Data.Linq.Table<yacheykadb> yacheykadb
		{
			get
			{
				return this.GetTable<yacheykadb>();
			}
		}
		
		public System.Data.Linq.Table<energydb> energydb
		{
			get
			{
				return this.GetTable<energydb>();
			}
		}
		
		public System.Data.Linq.Table<expdb> expdb
		{
			get
			{
				return this.GetTable<expdb>();
			}
		}
		
		public System.Data.Linq.Table<globalitemdb> globalitemdb
		{
			get
			{
				return this.GetTable<globalitemdb>();
			}
		}
		
		public System.Data.Linq.Table<inventorydb> inventorydb
		{
			get
			{
				return this.GetTable<inventorydb>();
			}
		}
		
		public System.Data.Linq.Table<moneydb> moneydb
		{
			get
			{
				return this.GetTable<moneydb>();
			}
		}
		
		public System.Data.Linq.Table<racedb> racedb
		{
			get
			{
				return this.GetTable<racedb>();
			}
		}
		
		public System.Data.Linq.Table<racetypedb> racetypedb
		{
			get
			{
				return this.GetTable<racetypedb>();
			}
		}
		
		public System.Data.Linq.Table<settingsdb> settingsdb
		{
			get
			{
				return this.GetTable<settingsdb>();
			}
		}
		
		public System.Data.Linq.Table<shipdb> shipdb
		{
			get
			{
				return this.GetTable<shipdb>();
			}
		}
		
		public System.Data.Linq.Table<stagedb> stagedb
		{
			get
			{
				return this.GetTable<stagedb>();
			}
		}
		
		public System.Data.Linq.Table<userdb> userdb
		{
			get
			{
				return this.GetTable<userdb>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.authkeydb")]
	public partial class authkeydb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _authkey;
		
		private System.Nullable<System.DateTime> _datetime;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnauthkeyChanging(string value);
    partial void OnauthkeyChanged();
    partial void OndatetimeChanging(System.Nullable<System.DateTime> value);
    partial void OndatetimeChanged();
    #endregion
		
		public authkeydb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_authkey", DbType="NChar(10)")]
		public string authkey
		{
			get
			{
				return this._authkey;
			}
			set
			{
				if ((this._authkey != value))
				{
					this.OnauthkeyChanging(value);
					this.SendPropertyChanging();
					this._authkey = value;
					this.SendPropertyChanged("authkey");
					this.OnauthkeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> datetime
		{
			get
			{
				return this._datetime;
			}
			set
			{
				if ((this._datetime != value))
				{
					this.OndatetimeChanging(value);
					this.SendPropertyChanging();
					this._datetime = value;
					this.SendPropertyChanged("datetime");
					this.OndatetimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.yacheykadb")]
	public partial class yacheykadb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private System.Nullable<int> _type;
		
		private System.Nullable<int> _item_id;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OntypeChanging(System.Nullable<int> value);
    partial void OntypeChanged();
    partial void Onitem_idChanging(System.Nullable<int> value);
    partial void Onitem_idChanged();
    #endregion
		
		public yacheykadb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_id", DbType="Int")]
		public System.Nullable<int> item_id
		{
			get
			{
				return this._item_id;
			}
			set
			{
				if ((this._item_id != value))
				{
					this.Onitem_idChanging(value);
					this.SendPropertyChanging();
					this._item_id = value;
					this.SendPropertyChanged("item_id");
					this.Onitem_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.energydb")]
	public partial class energydb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _energylimit;
		
		private System.Nullable<int> _energycount;
		
		private System.Nullable<System.DateTime> _datetime;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnenergylimitChanging(System.Nullable<int> value);
    partial void OnenergylimitChanged();
    partial void OnenergycountChanging(System.Nullable<int> value);
    partial void OnenergycountChanged();
    partial void OndatetimeChanging(System.Nullable<System.DateTime> value);
    partial void OndatetimeChanged();
    #endregion
		
		public energydb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_energylimit", DbType="Int")]
		public System.Nullable<int> energylimit
		{
			get
			{
				return this._energylimit;
			}
			set
			{
				if ((this._energylimit != value))
				{
					this.OnenergylimitChanging(value);
					this.SendPropertyChanging();
					this._energylimit = value;
					this.SendPropertyChanged("energylimit");
					this.OnenergylimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_energycount", DbType="Int")]
		public System.Nullable<int> energycount
		{
			get
			{
				return this._energycount;
			}
			set
			{
				if ((this._energycount != value))
				{
					this.OnenergycountChanging(value);
					this.SendPropertyChanging();
					this._energycount = value;
					this.SendPropertyChanged("energycount");
					this.OnenergycountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datetime", DbType="Date")]
		public System.Nullable<System.DateTime> datetime
		{
			get
			{
				return this._datetime;
			}
			set
			{
				if ((this._datetime != value))
				{
					this.OndatetimeChanging(value);
					this.SendPropertyChanging();
					this._datetime = value;
					this.SendPropertyChanged("datetime");
					this.OndatetimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.expdb")]
	public partial class expdb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _expcount;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnexpcountChanging(System.Nullable<int> value);
    partial void OnexpcountChanged();
    #endregion
		
		public expdb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expcount", DbType="Int")]
		public System.Nullable<int> expcount
		{
			get
			{
				return this._expcount;
			}
			set
			{
				if ((this._expcount != value))
				{
					this.OnexpcountChanging(value);
					this.SendPropertyChanging();
					this._expcount = value;
					this.SendPropertyChanged("expcount");
					this.OnexpcountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.globalitemdb")]
	public partial class globalitemdb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _type;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OntypeChanging(System.Nullable<int> value);
    partial void OntypeChanged();
    #endregion
		
		public globalitemdb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.inventorydb")]
	public partial class inventorydb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _idmassyacheek;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnidmassyacheekChanging(string value);
    partial void OnidmassyacheekChanged();
    #endregion
		
		public inventorydb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idmassyacheek", DbType="VarChar(MAX)")]
		public string idmassyacheek
		{
			get
			{
				return this._idmassyacheek;
			}
			set
			{
				if ((this._idmassyacheek != value))
				{
					this.OnidmassyacheekChanging(value);
					this.SendPropertyChanging();
					this._idmassyacheek = value;
					this.SendPropertyChanged("idmassyacheek");
					this.OnidmassyacheekChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.moneydb")]
	public partial class moneydb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _gold;
		
		private System.Nullable<int> _oensh;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OngoldChanging(System.Nullable<int> value);
    partial void OngoldChanged();
    partial void OnoenshChanging(System.Nullable<int> value);
    partial void OnoenshChanged();
    #endregion
		
		public moneydb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gold", DbType="Int")]
		public System.Nullable<int> gold
		{
			get
			{
				return this._gold;
			}
			set
			{
				if ((this._gold != value))
				{
					this.OngoldChanging(value);
					this.SendPropertyChanging();
					this._gold = value;
					this.SendPropertyChanged("gold");
					this.OngoldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oensh", DbType="Int")]
		public System.Nullable<int> oensh
		{
			get
			{
				return this._oensh;
			}
			set
			{
				if ((this._oensh != value))
				{
					this.OnoenshChanging(value);
					this.SendPropertyChanging();
					this._oensh = value;
					this.SendPropertyChanged("oensh");
					this.OnoenshChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.racedb")]
	public partial class racedb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _type;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OntypeChanging(System.Nullable<int> value);
    partial void OntypeChanged();
    #endregion
		
		public racedb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.racetypedb")]
	public partial class racetypedb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _damage;
		
		private System.Nullable<int> _hp;
		
		private System.Nullable<int> _mp;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OndamageChanging(System.Nullable<int> value);
    partial void OndamageChanged();
    partial void OnhpChanging(System.Nullable<int> value);
    partial void OnhpChanged();
    partial void OnmpChanging(System.Nullable<int> value);
    partial void OnmpChanged();
    #endregion
		
		public racetypedb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_damage", DbType="Int")]
		public System.Nullable<int> damage
		{
			get
			{
				return this._damage;
			}
			set
			{
				if ((this._damage != value))
				{
					this.OndamageChanging(value);
					this.SendPropertyChanging();
					this._damage = value;
					this.SendPropertyChanged("damage");
					this.OndamageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hp", DbType="Int")]
		public System.Nullable<int> hp
		{
			get
			{
				return this._hp;
			}
			set
			{
				if ((this._hp != value))
				{
					this.OnhpChanging(value);
					this.SendPropertyChanging();
					this._hp = value;
					this.SendPropertyChanged("hp");
					this.OnhpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mp", DbType="Int")]
		public System.Nullable<int> mp
		{
			get
			{
				return this._mp;
			}
			set
			{
				if ((this._mp != value))
				{
					this.OnmpChanging(value);
					this.SendPropertyChanging();
					this._mp = value;
					this.SendPropertyChanged("mp");
					this.OnmpChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.settingsdb")]
	public partial class settingsdb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _music;
		
		private System.Nullable<int> _sound;
		
		private System.Nullable<int> _volume;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnmusicChanging(System.Nullable<int> value);
    partial void OnmusicChanged();
    partial void OnsoundChanging(System.Nullable<int> value);
    partial void OnsoundChanged();
    partial void OnvolumeChanging(System.Nullable<int> value);
    partial void OnvolumeChanged();
    #endregion
		
		public settingsdb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_music", DbType="Int")]
		public System.Nullable<int> music
		{
			get
			{
				return this._music;
			}
			set
			{
				if ((this._music != value))
				{
					this.OnmusicChanging(value);
					this.SendPropertyChanging();
					this._music = value;
					this.SendPropertyChanged("music");
					this.OnmusicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sound", DbType="Int")]
		public System.Nullable<int> sound
		{
			get
			{
				return this._sound;
			}
			set
			{
				if ((this._sound != value))
				{
					this.OnsoundChanging(value);
					this.SendPropertyChanging();
					this._sound = value;
					this.SendPropertyChanged("sound");
					this.OnsoundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_volume", DbType="Int")]
		public System.Nullable<int> volume
		{
			get
			{
				return this._volume;
			}
			set
			{
				if ((this._volume != value))
				{
					this.OnvolumeChanging(value);
					this.SendPropertyChanging();
					this._volume = value;
					this.SendPropertyChanged("volume");
					this.OnvolumeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.shipdb")]
	public partial class shipdb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _shiptype;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnshiptypeChanging(System.Nullable<int> value);
    partial void OnshiptypeChanged();
    #endregion
		
		public shipdb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shiptype", DbType="Int")]
		public System.Nullable<int> shiptype
		{
			get
			{
				return this._shiptype;
			}
			set
			{
				if ((this._shiptype != value))
				{
					this.OnshiptypeChanging(value);
					this.SendPropertyChanging();
					this._shiptype = value;
					this.SendPropertyChanged("shiptype");
					this.OnshiptypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.stagedb")]
	public partial class stagedb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _planet1;
		
		private System.Nullable<int> _planet2;
		
		private System.Nullable<int> _planet3;
		
		private System.Nullable<int> _planet4;
		
		private System.Nullable<int> _planet5;
		
		private System.Nullable<int> _planet6;
		
		private System.Nullable<int> _planet7;
		
		private System.Nullable<int> _planet8;
		
		private System.Nullable<int> _planet9;
		
		private System.Nullable<int> _planet10;
		
		private System.Nullable<int> _planet11;
		
		private System.Nullable<int> _planet12;
		
		private System.Nullable<int> _planet13;
		
		private System.Nullable<int> _planet14;
		
		private System.Nullable<int> _planet15;
		
		private System.Nullable<int> _lastplanetwin;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onplanet1Changing(System.Nullable<int> value);
    partial void Onplanet1Changed();
    partial void Onplanet2Changing(System.Nullable<int> value);
    partial void Onplanet2Changed();
    partial void Onplanet3Changing(System.Nullable<int> value);
    partial void Onplanet3Changed();
    partial void Onplanet4Changing(System.Nullable<int> value);
    partial void Onplanet4Changed();
    partial void Onplanet5Changing(System.Nullable<int> value);
    partial void Onplanet5Changed();
    partial void Onplanet6Changing(System.Nullable<int> value);
    partial void Onplanet6Changed();
    partial void Onplanet7Changing(System.Nullable<int> value);
    partial void Onplanet7Changed();
    partial void Onplanet8Changing(System.Nullable<int> value);
    partial void Onplanet8Changed();
    partial void Onplanet9Changing(System.Nullable<int> value);
    partial void Onplanet9Changed();
    partial void Onplanet10Changing(System.Nullable<int> value);
    partial void Onplanet10Changed();
    partial void Onplanet11Changing(System.Nullable<int> value);
    partial void Onplanet11Changed();
    partial void Onplanet12Changing(System.Nullable<int> value);
    partial void Onplanet12Changed();
    partial void Onplanet13Changing(System.Nullable<int> value);
    partial void Onplanet13Changed();
    partial void Onplanet14Changing(System.Nullable<int> value);
    partial void Onplanet14Changed();
    partial void Onplanet15Changing(System.Nullable<int> value);
    partial void Onplanet15Changed();
    partial void OnlastplanetwinChanging(System.Nullable<int> value);
    partial void OnlastplanetwinChanged();
    #endregion
		
		public stagedb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planet1", DbType="Int")]
		public System.Nullable<int> planet1
		{
			get
			{
				return this._planet1;
			}
			set
			{
				if ((this._planet1 != value))
				{
					this.Onplanet1Changing(value);
					this.SendPropertyChanging();
					this._planet1 = value;
					this.SendPropertyChanged("planet1");
					this.Onplanet1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planet2", DbType="Int")]
		public System.Nullable<int> planet2
		{
			get
			{
				return this._planet2;
			}
			set
			{
				if ((this._planet2 != value))
				{
					this.Onplanet2Changing(value);
					this.SendPropertyChanging();
					this._planet2 = value;
					this.SendPropertyChanged("planet2");
					this.Onplanet2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planet3", DbType="Int")]
		public System.Nullable<int> planet3
		{
			get
			{
				return this._planet3;
			}
			set
			{
				if ((this._planet3 != value))
				{
					this.Onplanet3Changing(value);
					this.SendPropertyChanging();
					this._planet3 = value;
					this.SendPropertyChanged("planet3");
					this.Onplanet3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planet4", DbType="Int")]
		public System.Nullable<int> planet4
		{
			get
			{
				return this._planet4;
			}
			set
			{
				if ((this._planet4 != value))
				{
					this.Onplanet4Changing(value);
					this.SendPropertyChanging();
					this._planet4 = value;
					this.SendPropertyChanged("planet4");
					this.Onplanet4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planet5", DbType="Int")]
		public System.Nullable<int> planet5
		{
			get
			{
				return this._planet5;
			}
			set
			{
				if ((this._planet5 != value))
				{
					this.Onplanet5Changing(value);
					this.SendPropertyChanging();
					this._planet5 = value;
					this.SendPropertyChanged("planet5");
					this.Onplanet5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planet6", DbType="Int")]
		public System.Nullable<int> planet6
		{
			get
			{
				return this._planet6;
			}
			set
			{
				if ((this._planet6 != value))
				{
					this.Onplanet6Changing(value);
					this.SendPropertyChanging();
					this._planet6 = value;
					this.SendPropertyChanged("planet6");
					this.Onplanet6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planet7", DbType="Int")]
		public System.Nullable<int> planet7
		{
			get
			{
				return this._planet7;
			}
			set
			{
				if ((this._planet7 != value))
				{
					this.Onplanet7Changing(value);
					this.SendPropertyChanging();
					this._planet7 = value;
					this.SendPropertyChanged("planet7");
					this.Onplanet7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planet8", DbType="Int")]
		public System.Nullable<int> planet8
		{
			get
			{
				return this._planet8;
			}
			set
			{
				if ((this._planet8 != value))
				{
					this.Onplanet8Changing(value);
					this.SendPropertyChanging();
					this._planet8 = value;
					this.SendPropertyChanged("planet8");
					this.Onplanet8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planet9", DbType="Int")]
		public System.Nullable<int> planet9
		{
			get
			{
				return this._planet9;
			}
			set
			{
				if ((this._planet9 != value))
				{
					this.Onplanet9Changing(value);
					this.SendPropertyChanging();
					this._planet9 = value;
					this.SendPropertyChanged("planet9");
					this.Onplanet9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planet10", DbType="Int")]
		public System.Nullable<int> planet10
		{
			get
			{
				return this._planet10;
			}
			set
			{
				if ((this._planet10 != value))
				{
					this.Onplanet10Changing(value);
					this.SendPropertyChanging();
					this._planet10 = value;
					this.SendPropertyChanged("planet10");
					this.Onplanet10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planet11", DbType="Int")]
		public System.Nullable<int> planet11
		{
			get
			{
				return this._planet11;
			}
			set
			{
				if ((this._planet11 != value))
				{
					this.Onplanet11Changing(value);
					this.SendPropertyChanging();
					this._planet11 = value;
					this.SendPropertyChanged("planet11");
					this.Onplanet11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planet12", DbType="Int")]
		public System.Nullable<int> planet12
		{
			get
			{
				return this._planet12;
			}
			set
			{
				if ((this._planet12 != value))
				{
					this.Onplanet12Changing(value);
					this.SendPropertyChanging();
					this._planet12 = value;
					this.SendPropertyChanged("planet12");
					this.Onplanet12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planet13", DbType="Int")]
		public System.Nullable<int> planet13
		{
			get
			{
				return this._planet13;
			}
			set
			{
				if ((this._planet13 != value))
				{
					this.Onplanet13Changing(value);
					this.SendPropertyChanging();
					this._planet13 = value;
					this.SendPropertyChanged("planet13");
					this.Onplanet13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planet14", DbType="Int")]
		public System.Nullable<int> planet14
		{
			get
			{
				return this._planet14;
			}
			set
			{
				if ((this._planet14 != value))
				{
					this.Onplanet14Changing(value);
					this.SendPropertyChanging();
					this._planet14 = value;
					this.SendPropertyChanged("planet14");
					this.Onplanet14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planet15", DbType="Int")]
		public System.Nullable<int> planet15
		{
			get
			{
				return this._planet15;
			}
			set
			{
				if ((this._planet15 != value))
				{
					this.Onplanet15Changing(value);
					this.SendPropertyChanging();
					this._planet15 = value;
					this.SendPropertyChanged("planet15");
					this.Onplanet15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastplanetwin", DbType="Int")]
		public System.Nullable<int> lastplanetwin
		{
			get
			{
				return this._lastplanetwin;
			}
			set
			{
				if ((this._lastplanetwin != value))
				{
					this.OnlastplanetwinChanging(value);
					this.SendPropertyChanging();
					this._lastplanetwin = value;
					this.SendPropertyChanged("lastplanetwin");
					this.OnlastplanetwinChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userdb")]
	public partial class userdb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nickname;
		
		private System.Nullable<int> _Idsbase;
		
		private System.Nullable<System.DateTime> _Timecreate;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNicknameChanging(string value);
    partial void OnNicknameChanged();
    partial void OnIdsbaseChanging(System.Nullable<int> value);
    partial void OnIdsbaseChanged();
    partial void OnTimecreateChanging(System.Nullable<System.DateTime> value);
    partial void OnTimecreateChanged();
    #endregion
		
		public userdb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nickname", DbType="NChar(10)")]
		public string Nickname
		{
			get
			{
				return this._Nickname;
			}
			set
			{
				if ((this._Nickname != value))
				{
					this.OnNicknameChanging(value);
					this.SendPropertyChanging();
					this._Nickname = value;
					this.SendPropertyChanged("Nickname");
					this.OnNicknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idsbase", DbType="Int")]
		public System.Nullable<int> Idsbase
		{
			get
			{
				return this._Idsbase;
			}
			set
			{
				if ((this._Idsbase != value))
				{
					this.OnIdsbaseChanging(value);
					this.SendPropertyChanging();
					this._Idsbase = value;
					this.SendPropertyChanged("Idsbase");
					this.OnIdsbaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timecreate", DbType="DateTime")]
		public System.Nullable<System.DateTime> Timecreate
		{
			get
			{
				return this._Timecreate;
			}
			set
			{
				if ((this._Timecreate != value))
				{
					this.OnTimecreateChanging(value);
					this.SendPropertyChanging();
					this._Timecreate = value;
					this.SendPropertyChanged("Timecreate");
					this.OnTimecreateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
